
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS SALE_STATUS;


CREATE TABLE MEMBER (
	MEMBER_ID SERIAL NOT NULL,
	LOGIN_ID  VARCHAR(255) NOT NULL,
	PASSWORD  VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	ZIPCODE CHAR(7) NOT NULL,
	PREFECTURE VARCHAR(255) NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PHONE_NUMBER VARCHAR(255) NOT NULL,
	PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE CATEGORY (
	CATEGORY_ID SERIAL NOT NULL,
	CATEGORY_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE SALE_STATUS(
	SALE_STATUS_ID SERIAL NOT NULL,
	SALE_STATUS_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (SALE_STATUS_ID)
);

CREATE TABLE BOOK (
	BOOK_ID SERIAL NOT NULL,
	MEMBER_ID SERIAL NOT NULL REFERENCES MEMBER(MEMBER_ID),
	ISBN_CODE VARCHAR(255) NOT NULL,
	BOOK_NAME VARCHAR(255) NOT NULL,
	AUTHOR VARCHAR(255),
	PRICE INTEGER ,
	ISSUE_DATE DATE ,
	COMMENT VARCHAR(255),
	CATEGORY_ID SERIAL REFERENCES CATEGORY(CATEGORY_ID),
	SALE_STATUS_ID SERIAL REFERENCES SALE_STATUS(SALE_STATUS_ID),
	PRIMARY KEY (BOOK_ID)
);